version: '3'

networks:
  web-network:

services:
  # docker-influxdb:
  #   image: influxdb:2.4
  #   container_name: influxdb
  #   restart: always
  #   ports:
  #     - "8086:8086" #HTTP UI and API port
  #   environment:
  #     DOCKER_INFLUXDB_INIT_MODE: "setup"
  #     DOCKER_INFLUXDB_INIT_USERNAME: "root" #创建管理员用户
  #     DOCKER_INFLUXDB_INIT_PASSWORD: "a123456a" #创建管理员密码，太简单会报错
  #     DOCKER_INFLUXDB_INIT_ORG: "miot-tracer" #组织名称
  #     DOCKER_INFLUXDB_INIT_BUCKET: "node1"
  #   volumes:
  #     - "./influxdb/data:/var/lib/influxdb2"
  #     - "./influxdb/config:/etc/influxdb2"
  #   networks:
  #     - web-network

  # miot-tracer-redis:
  #   image: redis
  #   container_name: redis
  #   command: redis-server /etc/redis/redis.conf --appendonly yes
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis-data/redis.conf:/etc/redis/redis.conf
  #     - ./redis-data/redis:/data
  #   restart: always
  #   networks:
  #     - web-network
  
  # redis-insight:
  #   image: redislabs/redisinsight:latest
  #   ports:
  #     - "8001:8001"
  #   restart: always
  #   networks:
  #     - web-network
  #   environment:
  #     - REDIS_URI=redis://miot-tracer-redis:6379
  #   links:
  #     - miot-tracer-redis

#-----------------node-----------------
  miot-tracer-node_1:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_1
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_1.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro          #把宿主机的证书文件挂载到容器中
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=1
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node1
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis

  miot-tracer-node_2:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_2
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_2.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=2
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node2
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis

  miot-tracer-node_3:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_3
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_3.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=3
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node3
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis
    

  miot-tracer-node_4:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_4
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_4.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=4
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node4
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis
    
  miot-tracer-node_5:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_5
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_5.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=5
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node5
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis

  miot-tracer-node_6:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_6
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_6.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=6
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node6
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis
    
  miot-tracer-node_7:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_7
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_7.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=7
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node7
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis
    
  miot-tracer-node_8:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_8
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_8.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=8
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node8
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis

  miot-tracer-node_9:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_9
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_9.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=9
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node9
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis

  miot-tracer-node_10:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_10
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_10.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=10
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node10
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis

  miot-tracer-node_11:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_11
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_11.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=11
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node11
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis
  
  miot-tracer-node_12:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_12
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_12.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=12
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node12
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis
    
  miot-tracer-node_13:  
    image: debian:bookworm-slim
    container_name: miot-tracer-node_13
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_13.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=13
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node13
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis
  
  miot-tracer-node_14:  
    image: debian:bookworm-slim
    container_name: miot-tracer-node_14
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_14.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=14
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node14
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis
  
  miot-tracer-node_15:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_15
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_15.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=15
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node15
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis
    
  miot-tracer-node_16:
    image: debian:bookworm-slim
    container_name: miot-tracer-node_16
    volumes:
      - ./miot_tracing_go:/miot_tracing_go
      - ./logFile/miot_tracer_log_16.json:/logFile/miot_tracer_log.json
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/miot_tracing_go"]
    environment:
      - NODE_ID=16
      - INFLUXDB_TOKEN=J_xeoyLkPQFHBilXk4ELHjV85A7fFtIJvlo3GTjmKnF3QPZU63H7N0FH5_x7JBMPy3MRvVwoeoW0rnReDyLuPg==
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=node16
      - REDIS_URL=redis:6379
    networks:
      - web-network
    # depends_on:
      # - docker-influxdb
      # - miot-tracer-redis